<?php
namespace Database\Seeders;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use App\Models\LanguageTranslate;

class LanguageTranslateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $translations = [
            ['model' => ' Navigation', 'label' => 'navigation_navigation_dashboard', 'translation' => '   dashboard'],
            ['model' => ' Navigation', 'label' => 'navigation_navigation_manage_users', 'translation' => '   Manage Users'],
            ['model' => ' Navigation', 'label' => 'navigation_navigation_permissions', 'translation' => '   roles and permissions'],
            ['model' => ' Navigation', 'label' => 'navigation_navigation_roles_list', 'translation' => '   roles list'],
            ['model' => ' Navigation', 'label' => 'navigation_navigation_users_list', 'translation' => '   users list'],
            ['model' => ' Navigation', 'label' => 'navigation_navigation_countries', 'translation' => '   countries'],
            ['model' => ' Navigation', 'label' => 'navigation_navigation_manage_language', 'translation' => '   languages'],
            ['model' => ' Navigation', 'label' => 'navigation_navigation_language_translation', 'translation' => '  language translation'],
            ['model' => ' General', 'label' => 'general_general_action', 'translation' => '  Action'],
            ['model' => ' General', 'label' => 'general_general_save', 'translation' => '  Save'],
            ['model' => ' General', 'label' => 'general_general_update', 'translation' => '  Update'],
            ['model' => ' General', 'label' => 'general_general_close', 'translation' => '  Close'],
            ['model' => ' General', 'label' => 'general_general_return', 'translation' => '  Return'],
            ['model' => ' General', 'label' => 'general_general_configuration', 'translation' => '  Configuration'],
            ['model' => ' General', 'label' => 'general_general_search', 'translation' => '  Search'],
            ['model' => ' General', 'label' => 'general_general_add', 'translation' => '  Add'],
            ['model' => ' General', 'label' => 'general_general_select', 'translation' => '  Choose One'],
            ['model' => ' General', 'label' => 'general_general_super', 'translation' => '  Super'],
            ['model' => ' General', 'label' => 'general_general_delete_selected', 'translation' => '  Delete selected'],
            ['model' => ' General', 'label' => 'general_general_restore_selected', 'translation' => '  Restore selected'],
            ['model' => ' General', 'label' => 'general_general_activate_selected', 'translation' => '  Activate selected'],
            ['model' => ' Language', 'label' => 'language_action_add', 'translation' => '  Add language'],
            ['model' => ' Language', 'label' => 'language_action_show', 'translation' => '  Show language'],
            ['model' => ' Language', 'label' => 'language_action_edit', 'translation' => '  Edit language'],
            ['model' => ' Language', 'label' => 'language_action_delete', 'translation' => '  Delete language'],
            ['model' => ' Language', 'label' => 'language_action_restore', 'translation' => '  Restore language'],
            ['model' => ' Language', 'label' => 'language_message_add', 'translation' => '  Language successfully created'],
            ['model' => ' Language', 'label' => 'language_message_show', 'translation' => '  Language successfully showed'],
            ['model' => ' Language', 'label' => 'language_message_edit', 'translation' => '  Language successfully updated'],
            ['model' => ' Language', 'label' => 'language_message_delete', 'translation' => '  Language successfully deleted'],
            ['model' => ' Language', 'label' => 'language_message_restore', 'translation' => '  Language successfully restored'],
            ['model' => ' Language', 'label' => 'language_message_activated', 'translation' => '  Language has been successfully activated'],
            ['model' => ' Language', 'label' => 'language_message_inactivated', 'translation' => '  Language has been successfully inactivated'],
            ['model' => ' Language', 'label' => 'language_form_manage_languages', 'translation' => '  Manage languages'],
            ['model' => ' Language', 'label' => 'language_form_languages_list', 'translation' => '  List of languages'],
            ['model' => ' Language', 'label' => 'language_form_deleted_languages_list', 'translation' => '  List deleted languages'],
            ['model' => ' Language', 'label' => 'language_form_manage_deleted_languages', 'translation' => '  Manage deleted languages'],
            ['model' => ' Language', 'label' => 'language_table_name', 'translation' => '  Name'],
            ['model' => ' Language', 'label' => 'language_form_name', 'translation' => '  Name'],
            ['model' => ' Language', 'label' => 'language_form_name_placeholder', 'translation' => '  Enter name'],
            ['model' => ' Language', 'label' => 'language_table_locale', 'translation' => '  Locale'],
            ['model' => ' Language', 'label' => 'language_form_locale', 'translation' => '  Locale'],
            ['model' => ' Language', 'label' => 'language_form_locale_placeholder', 'translation' => '  Enter locale'],
            ['model' => ' Language', 'label' => 'language_table_isDefault', 'translation' => '  IsDefault'],
            ['model' => ' Language', 'label' => 'language_form_isDefault', 'translation' => '  IsDefault'],
            ['model' => ' Language', 'label' => 'language_form_isDefault_placeholder', 'translation' => '  Enter isDefault'],
            ['model' => ' Language', 'label' => 'language_table_status', 'translation' => '  Status'],
            ['model' => ' Language', 'label' => 'language_form_status', 'translation' => '  Status'],
            ['model' => ' Language', 'label' => 'language_form_status_placeholder', 'translation' => '  Enter status'],
            ['model' => ' Language', 'label' => 'language_table_visible', 'translation' => '  Visible'],
            ['model' => ' Language', 'label' => 'language_form_visible', 'translation' => '  Visible'],
            ['model' => ' Language', 'label' => 'language_form_visible_placeholder', 'translation' => '  Enter visible'],
            ['model' => ' Language', 'label' => 'language_table_flag_path', 'translation' => '  Flag path'],
            ['model' => ' Language', 'label' => 'language_form_flag_path', 'translation' => '  Flag path'],
            ['model' => ' Language', 'label' => 'language_form_flag_path_placeholder', 'translation' => '  Enter flag path'],
            ['model' => ' Language', 'label' => 'language_table_created_at', 'translation' => '  Created at'],
            ['model' => ' Language', 'label' => 'language_form_created_at', 'translation' => '  Created at'],
            ['model' => ' Language', 'label' => 'language_form_created_at_placeholder', 'translation' => '  Enter created at'],
            ['model' => ' Language', 'label' => 'language_table_updated_at', 'translation' => '  Updated at'],
            ['model' => ' Language', 'label' => 'language_form_updated_at', 'translation' => '  Updated at'],
            ['model' => ' Language', 'label' => 'language_form_updated_at_placeholder', 'translation' => '  Enter updated at'],
            ['model' => ' Role', 'label' => 'role_action_add', 'translation' => '  Add role'],
            ['model' => ' Role', 'label' => 'role_action_show', 'translation' => '  Show role'],
            ['model' => ' Role', 'label' => 'role_action_edit', 'translation' => '  Edit role'],
            ['model' => ' Role', 'label' => 'role_action_delete', 'translation' => '  Delete role'],
            ['model' => ' Role', 'label' => 'role_action_restore', 'translation' => '  Restore role'],
            ['model' => ' Role', 'label' => 'role_message_add', 'translation' => '  Role successfully created'],
            ['model' => ' Role', 'label' => 'role_message_show', 'translation' => '  Role successfully showed'],
            ['model' => ' Role', 'label' => 'role_message_edit', 'translation' => '  Role successfully updated'],
            ['model' => ' Role', 'label' => 'role_message_delete', 'translation' => '  Role successfully deleted'],
            ['model' => ' Role', 'label' => 'role_message_restore', 'translation' => '  Role successfully restored'],
            ['model' => ' Role', 'label' => 'role_message_activated', 'translation' => '  Role has been successfully activated'],
            ['model' => ' Role', 'label' => 'role_message_inactivated', 'translation' => '  Role has been successfully inactivated'],
            ['model' => ' Role', 'label' => 'role_form_manage_roles', 'translation' => '  Manage roles'],
            ['model' => ' Role', 'label' => 'role_form_roles_list', 'translation' => '  List of roles'],
            ['model' => ' Role', 'label' => 'role_form_deleted_roles_list', 'translation' => '  List deleted roles'],
            ['model' => ' Role', 'label' => 'role_form_manage_deleted_roles', 'translation' => '  Manage deleted roles'],
            ['model' => ' Role', 'label' => 'role_table_name', 'translation' => '  Name'],
            ['model' => ' Role', 'label' => 'role_form_name', 'translation' => '  Name'],
            ['model' => ' Role', 'label' => 'role_form_name_placeholder', 'translation' => '  Enter name'],
            ['model' => ' Role', 'label' => 'role_table_guard_name', 'translation' => '  Guard name'],
            ['model' => ' Role', 'label' => 'role_form_guard_name', 'translation' => '  Guard name'],
            ['model' => ' Role', 'label' => 'role_form_guard_name_placeholder', 'translation' => '  Enter guard name'],
            ['model' => ' Role', 'label' => 'role_table_created_at', 'translation' => '  Created at'],
            ['model' => ' Role', 'label' => 'role_form_created_at', 'translation' => '  Created at'],
            ['model' => ' Role', 'label' => 'role_form_created_at_placeholder', 'translation' => '  Enter created at'],
            ['model' => ' Role', 'label' => 'role_table_updated_at', 'translation' => '  Updated at'],
            ['model' => ' Role', 'label' => 'role_form_updated_at', 'translation' => '  Updated at'],
            ['model' => ' Role', 'label' => 'role_form_updated_at_placeholder', 'translation' => '  Enter updated at'],
            ['model' => ' User', 'label' => 'user_action_add', 'translation' => '  Add user'],
            ['model' => ' User', 'label' => 'user_action_show', 'translation' => '  Show user'],
            ['model' => ' User', 'label' => 'user_action_edit', 'translation' => '  Edit user'],
            ['model' => ' User', 'label' => 'user_action_delete', 'translation' => '  Delete user'],
            ['model' => ' User', 'label' => 'user_action_restore', 'translation' => '  Restore user'],
            ['model' => ' User', 'label' => 'user_message_add', 'translation' => '  User successfully created'],
            ['model' => ' User', 'label' => 'user_message_show', 'translation' => '  User successfully showed'],
            ['model' => ' User', 'label' => 'user_message_edit', 'translation' => '  User successfully updated'],
            ['model' => ' User', 'label' => 'user_message_delete', 'translation' => '  User successfully deleted'],
            ['model' => ' User', 'label' => 'user_message_restore', 'translation' => '  User successfully restored'],
            ['model' => ' User', 'label' => 'user_message_activated', 'translation' => '  User has been successfully activated'],
            ['model' => ' User', 'label' => 'user_message_inactivated', 'translation' => '  User has been successfully inactivated'],
            ['model' => ' User', 'label' => 'user_form_manage_users', 'translation' => '  Manage users'],
            ['model' => ' User', 'label' => 'user_form_users_list', 'translation' => '  List of users'],
            ['model' => ' User', 'label' => 'user_form_deleted_users_list', 'translation' => '  List deleted users'],
            ['model' => ' User', 'label' => 'user_form_manage_deleted_users', 'translation' => '  Manage deleted users'],
            ['model' => ' User', 'label' => 'user_table_uuid', 'translation' => '  Uuid'],
            ['model' => ' User', 'label' => 'user_form_uuid', 'translation' => '  Uuid'],
            ['model' => ' User', 'label' => 'user_form_uuid_placeholder', 'translation' => '  Enter uuid'],
            ['model' => ' User', 'label' => 'user_table_first_name', 'translation' => '  First name'],
            ['model' => ' User', 'label' => 'user_form_first_name', 'translation' => '  First name'],
            ['model' => ' User', 'label' => 'user_form_first_name_placeholder', 'translation' => '  Enter first name'],
            ['model' => ' User', 'label' => 'user_table_last_name', 'translation' => '  Last name'],
            ['model' => ' User', 'label' => 'user_form_last_name', 'translation' => '  Last name'],
            ['model' => ' User', 'label' => 'user_form_last_name_placeholder', 'translation' => '  Enter last name'],
            ['model' => ' User', 'label' => 'user_table_username', 'translation' => '  Username'],
            ['model' => ' User', 'label' => 'user_form_username', 'translation' => '  Username'],
            ['model' => ' User', 'label' => 'user_form_username_placeholder', 'translation' => '  Enter username'],
            ['model' => ' User', 'label' => 'user_table_occupation', 'translation' => '  Occupation'],
            ['model' => ' User', 'label' => 'user_form_occupation', 'translation' => '  Occupation'],
            ['model' => ' User', 'label' => 'user_form_occupation_placeholder', 'translation' => '  Enter occupation'],
            ['model' => ' User', 'label' => 'user_table_email', 'translation' => '  Email'],
            ['model' => ' User', 'label' => 'user_form_email', 'translation' => '  Email'],
            ['model' => ' User', 'label' => 'user_form_email_placeholder', 'translation' => '  Enter email'],
            ['model' => ' User', 'label' => 'user_table_email_verified_at', 'translation' => '  Email verified at'],
            ['model' => ' User', 'label' => 'user_form_email_verified_at', 'translation' => '  Email verified at'],
            ['model' => ' User', 'label' => 'user_form_email_verified_at_placeholder', 'translation' => '  Enter email verified at'],
            ['model' => ' User', 'label' => 'user_table_language_id', 'translation' => '  Language'],
            ['model' => ' User', 'label' => 'user_form_language_id', 'translation' => '  Language'],
            ['model' => ' User', 'label' => 'user_form_language_id_placeholder', 'translation' => '  Enter language'],
            ['model' => ' User', 'label' => 'user_table_password', 'translation' => '  Password'],
            ['model' => ' User', 'label' => 'user_form_password', 'translation' => '  Password'],
            ['model' => ' User', 'label' => 'user_form_password_placeholder', 'translation' => '  Enter password'],
            ['model' => ' User', 'label' => 'user_table_isactive', 'translation' => '  Isactive'],
            ['model' => ' User', 'label' => 'user_form_isactive', 'translation' => '  Isactive'],
            ['model' => ' User', 'label' => 'user_form_isactive_placeholder', 'translation' => '  Enter isactive'],
            ['model' => ' User', 'label' => 'user_table_country_id', 'translation' => '  Country'],
            ['model' => ' User', 'label' => 'user_form_country_id', 'translation' => '  Country'],
            ['model' => ' User', 'label' => 'user_form_country_id_placeholder', 'translation' => '  Enter country'],
            ['model' => ' User', 'label' => 'user_table_state_id', 'translation' => '  State'],
            ['model' => ' User', 'label' => 'user_form_state_id', 'translation' => '  State'],
            ['model' => ' User', 'label' => 'user_form_state_placeholder', 'translation' => '  Enter state'],
            ['model' => ' User', 'label' => 'user_table_city_id', 'translation' => '  City'],
            ['model' => ' User', 'label' => 'user_form_city_id', 'translation' => '  City'],
            ['model' => ' User', 'label' => 'user_form_city_placeholder', 'translation' => '  Enter city'],
            ['model' => ' User', 'label' => 'user_table_phone', 'translation' => '  Phone'],
            ['model' => ' User', 'label' => 'user_form_phone', 'translation' => '  Phone'],
            ['model' => ' User', 'label' => 'user_form_phone_placeholder', 'translation' => '  Enter phone'],
            ['model' => ' User', 'label' => 'user_table_picture', 'translation' => '  User'],
            ['model' => ' User', 'label' => 'user_form_picture', 'translation' => '  Picture'],
            ['model' => ' User', 'label' => 'user_form_picture_placeholder', 'translation' => '  Enter picture'],
            ['model' => ' User', 'label' => 'user_table_roles_name', 'translation' => '  Role'],
            ['model' => ' User', 'label' => 'user_form_roles_name', 'translation' => '  Roles name'],
            ['model' => ' User', 'label' => 'user_form_roles_name_placeholder', 'translation' => '  Enter roles name'],
            ['model' => ' User', 'label' => 'user_table_address', 'translation' => '  Address'],
            ['model' => ' User', 'label' => 'user_form_address', 'translation' => '  Address'],
            ['model' => ' User', 'label' => 'user_form_address_placeholder', 'translation' => '  Enter address'],
            ['model' => ' User', 'label' => 'user_table_code_postale', 'translation' => '  Code postale'],
            ['model' => ' User', 'label' => 'user_form_code_postale', 'translation' => '  Code postale'],
            ['model' => ' User', 'label' => 'user_form_code_postale_placeholder', 'translation' => '  Enter code postale'],
            ['model' => ' User', 'label' => 'user_table_gender', 'translation' => '  Gender'],
            ['model' => ' User', 'label' => 'user_form_gender', 'translation' => '  Gender'],
            ['model' => ' User', 'label' => 'user_form_gender_placeholder', 'translation' => '  Enter gender'],
            ['model' => ' User', 'label' => 'user_table_isSuperAdmin', 'translation' => '  IsSuperAdmin'],
            ['model' => ' User', 'label' => 'user_form_isSuperAdmin', 'translation' => '  IsSuperAdmin'],
            ['model' => ' User', 'label' => 'user_form_isSuperAdmin_placeholder', 'translation' => '  Enter isSuperAdmin'],
            ['model' => ' User', 'label' => 'user_table_last_login_at', 'translation' => '  Last login at'],
            ['model' => ' User', 'label' => 'user_form_last_login_at', 'translation' => '  Last login at'],
            ['model' => ' User', 'label' => 'user_form_last_login_at_placeholder', 'translation' => '  Enter last login at'],
            ['model' => ' User', 'label' => 'user_table_last_login_ip', 'translation' => '  Last login ip'],
            ['model' => ' User', 'label' => 'user_form_last_login_ip', 'translation' => '  Last login ip'],
            ['model' => ' User', 'label' => 'user_form_last_login_ip_placeholder', 'translation' => '  Enter last login ip'],
            ['model' => ' User', 'label' => 'user_table_remember_token', 'translation' => '  Remember token'],
            ['model' => ' User', 'label' => 'user_form_remember_token', 'translation' => '  Remember token'],
            ['model' => ' User', 'label' => 'user_form_remember_token_placeholder', 'translation' => '  Enter remember token'],
            ['model' => ' User', 'label' => 'user_table_created_at', 'translation' => '  Created at'],
            ['model' => ' User', 'label' => 'user_form_created_at', 'translation' => '  Created at'],
            ['model' => ' User', 'label' => 'user_form_created_at_placeholder', 'translation' => '  Enter created at'],
            ['model' => ' User', 'label' => 'user_table_updated_at', 'translation' => '  Updated at'],
            ['model' => ' User', 'label' => 'user_form_updated_at', 'translation' => '  Updated at'],
            ['model' => ' User', 'label' => 'user_form_updated_at_placeholder', 'translation' => '  Enter updated at'],
            ['model' => ' User', 'label' => 'user_table_deleted_at', 'translation' => '  Deleted at'],
            ['model' => ' User', 'label' => 'user_form_deleted_at', 'translation' => '  Deleted at'],
            ['model' => ' User', 'label' => 'user_form_deleted_at_placeholder', 'translation' => '  Enter deleted at'],
            ['model' => ' User', 'label' => 'user_form_password_confirmation', 'translation' => '  Confirm password'],
            ['model' => ' User', 'label' => 'user_form_password_confirmation_placeholder', 'translation' => '  Confirm password'],
            ['model' => ' User', 'label' => 'user_form_old_password', 'translation' => '  Old password'],
            ['model' => ' User', 'label' => 'user_form_old_password_placeholder', 'translation' => '  Enter the old password'],
            ['model' => ' User', 'label' => 'user_form_new_password', 'translation' => '  New password'],
            ['model' => ' User', 'label' => 'user_form_confirm_new_password', 'translation' => '  Confirm password'],
            ['model' => ' User', 'label' => 'user_form_overview', 'translation' => '  Overview'],
            ['model' => ' User', 'label' => 'user_form_new_password_placeholder', 'translation' => '  Enter the new password'],
            ['model' => ' User', 'label' => 'user_form_new_password_confirmation', 'translation' => '  New password confirmation'],
            ['model' => ' User', 'label' => 'user_form_security', 'translation' => '  Security'],
            ['model' => ' User', 'label' => 'user_form_new_password_confirmation_placeholder', 'translation' => '  Enter new password confirmation'],
            ['model' => ' User', 'label' => 'user_form_change_password', 'translation' => '  Change'],
            ['model' => ' User', 'label' => 'user_form_change_email_role', 'translation' => '  Change email and role'],
            ['model' => ' User', 'label' => 'user_message_current_password_error', 'translation' => '  There is an error in the current password'],
            ['model' => ' User', 'label' => 'user_message_update_email_role', 'translation' => '  The email and role have been successfully updated.'],
            ['model' => ' User', 'label' => 'user_message_picture', 'translation' => '  The picture have been successfully updated.'],
            ['model' => ' User', 'label' => 'user_message_overview', 'translation' => '  The overview have been successfully updated.'],
            ['model' => ' User', 'label' => 'user_message_password', 'translation' => '  The password have been successfully updated.'],
            ['model' => ' Setting', 'label' => 'setting_action_edit', 'translation' => '  Edit setting'],
            ['model' => ' Setting', 'label' => 'setting_action_delete', 'translation' => '  Delete setting'],
            ['model' => ' Setting', 'label' => 'setting_message_store', 'translation' => '  Setting successfully created'],
            ['model' => ' Setting', 'label' => 'setting_message_update', 'translation' => '  Setting successfully updated'],
            ['model' => ' Setting', 'label' => 'setting_message_delete', 'translation' => '  Setting successfully deleted'],
            ['model' => ' Setting', 'label' => 'setting_table_general', 'translation' => '  General'],
            ['model' => ' Setting', 'label' => 'setting_form_settings', 'translation' => '  Settings'],
            ['model' => ' Setting', 'label' => 'setting_form_system_name', 'translation' => '  System name'],
            ['model' => ' Setting', 'label' => 'setting_form_title', 'translation' => '  Title'],
            ['model' => ' Setting', 'label' => 'setting_form_address', 'translation' => '  Address'],
            ['model' => ' Setting', 'label' => 'setting_form_phone', 'translation' => '  Phone'],
            ['model' => ' Setting', 'label' => 'setting_form_system_name_placeholder', 'translation' => '  Enter system name'],
            ['model' => ' Setting', 'label' => 'setting_form_title_placeholder', 'translation' => '  Enter the title'],
            ['model' => ' Setting', 'label' => 'setting_form_address_placeholder', 'translation' => '  Enter the  adresse'],
            ['model' => ' Setting', 'label' => 'setting_form_copyrigth', 'translation' => '  Copyrigth'],
            ['model' => ' Setting', 'label' => 'setting_form_copyrigth_placeholder', 'translation' => '  Enter the  copyrigth'],
            ['model' => ' Setting', 'label' => 'setting_form_email', 'translation' => '  Email'],
            ['model' => ' Setting', 'label' => 'setting_form_email_placeholder', 'translation' => '  Enter the email'],
            ['model' => ' Setting', 'label' => 'setting_form_phone_placeholder', 'translation' => '  Enter the phone'],
            ['model' => ' Setting', 'label' => 'setting_form_manage_settings', 'translation' => '  Manage settings'],
            ['model' => ' Setting', 'label' => 'setting_form_settings_list', 'translation' => '  Setting list'],
            ['model' => ' Setting', 'label' => 'setting_form_logo', 'translation' => '  Logo'],
            ['model' => ' Setting', 'label' => 'setting_form_email_logo', 'translation' => '  Email logo'],
            ['model' => ' Setting', 'label' => 'setting_form_favicon', 'translation' => '  Favicon'],
            ['model' => ' Permission', 'label' => 'permission_action_add', 'translation' => '  Add permission'],
            ['model' => ' Permission', 'label' => 'permission_action_show', 'translation' => '  Show permission'],
            ['model' => ' Permission', 'label' => 'permission_action_edit', 'translation' => '  Edit permission'],
            ['model' => ' Permission', 'label' => 'permission_action_delete', 'translation' => '  Delete permission'],
            ['model' => ' Permission', 'label' => 'permission_action_restore', 'translation' => '  Restore permission'],
            ['model' => ' Permission', 'label' => 'permission_message_add', 'translation' => '  Permission successfully created'],
            ['model' => ' Permission', 'label' => 'permission_message_show', 'translation' => '  Permission successfully showed'],
            ['model' => ' Permission', 'label' => 'permission_message_edit', 'translation' => '  Permission successfully updated'],
            ['model' => ' Permission', 'label' => 'permission_message_delete', 'translation' => '  Permission successfully deleted'],
            ['model' => ' Permission', 'label' => 'permission_message_restore', 'translation' => '  Permission successfully restored'],
            ['model' => ' Permission', 'label' => 'permission_message_activated', 'translation' => '  Permission has been successfully activated'],
            ['model' => ' Permission', 'label' => 'permission_message_inactivated', 'translation' => '  Permission has been successfully inactivated'],
            ['model' => ' Permission', 'label' => 'permission_form_manage_permissions', 'translation' => '  Manage permissions'],
            ['model' => ' Permission', 'label' => 'permission_form_permissions_list', 'translation' => '  List of permissions'],
            ['model' => ' Permission', 'label' => 'permission_form_deleted_permissions_list', 'translation' => '  List deleted permissions'],
            ['model' => ' Permission', 'label' => 'permission_form_manage_deleted_permissions', 'translation' => '  Manage deleted permissions'],
            ['model' => ' Permission', 'label' => 'permission_message_delete_multiple', 'translation' => '  Selected permissions have been successfully deleted.'],
            ['model' => ' Permission', 'label' => 'permission_message_fail_delete_multiple', 'translation' => '  Failed to delete the selected permissions. Please try again.'],
            ['model' => ' Permission', 'label' => 'permission_message_restore_multiple', 'translation' => '  Selected permissions have been successfully restored.'],
            ['model' => ' Permission', 'label' => 'permission_message_fail_restore_multiple', 'translation' => '  Failed to restore the selected permissions. Please try again.'],
            ['model' => ' Permission', 'label' => 'permission_message_activate_multiple', 'translation' => '  Selected permissions have been successfully activated.'],
            ['model' => ' Permission', 'label' => 'permission_message_fail_activate_multiple', 'translation' => '  Failed to activate the selected permissions. Please try again.'],
            ['model' => ' Permission', 'label' => 'permission_table_name', 'translation' => '  Name'],
            ['model' => ' Permission', 'label' => 'permission_form_name', 'translation' => '  Name'],
            ['model' => ' Permission', 'label' => 'permission_form_name_placeholder', 'translation' => '  Enter name'],
            ['model' => ' Permission', 'label' => 'permission_table_libele', 'translation' => '  Libele'],
            ['model' => ' Permission', 'label' => 'permission_form_libele', 'translation' => '  Libele'],
            ['model' => ' Permission', 'label' => 'permission_form_libele_placeholder', 'translation' => '  Enter libele'],
            ['model' => ' Permission', 'label' => 'permission_table_guard_name', 'translation' => '  Guard name'],
            ['model' => ' Permission', 'label' => 'permission_form_guard_name', 'translation' => '  Guard name'],
            ['model' => ' Permission', 'label' => 'permission_form_guard_name_placeholder', 'translation' => '  Enter guard name'],
            ['model' => ' Permission', 'label' => 'permission_table_groupe_id', 'translation' => '  Groupe'],
            ['model' => ' Permission', 'label' => 'permission_form_groupe_id', 'translation' => '  Groupe'],
            ['model' => ' Permission', 'label' => 'permission_form_groupe_id_placeholder', 'translation' => '  Enter groupe'],
            ['model' => ' Permission', 'label' => 'permission_table_created_at', 'translation' => '  Created at'],
            ['model' => ' Permission', 'label' => 'permission_form_created_at', 'translation' => '  Created at'],
            ['model' => ' Permission', 'label' => 'permission_form_created_at_placeholder', 'translation' => '  Enter created at'],
            ['model' => ' Permission', 'label' => 'permission_table_updated_at', 'translation' => '  Updated at'],
            ['model' => ' Permission', 'label' => 'permission_form_updated_at', 'translation' => '  Updated at'],
            ['model' => ' Permission', 'label' => 'permission_form_updated_at_placeholder', 'translation' => '  Enter updated at'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_action_add', 'translation' => '  Add languagetranslate'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_action_show', 'translation' => '  Show languagetranslate'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_action_edit', 'translation' => '  Edit languagetranslate'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_action_delete', 'translation' => '  Delete languagetranslate'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_action_restore', 'translation' => '  Restore languagetranslate'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_message_add', 'translation' => '  LanguageTranslate successfully created'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_message_show', 'translation' => '  LanguageTranslate successfully showed'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_message_edit', 'translation' => '  LanguageTranslate successfully updated'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_message_delete', 'translation' => '  LanguageTranslate successfully deleted'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_message_restore', 'translation' => '  LanguageTranslate successfully restored'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_message_activated', 'translation' => '  LanguageTranslate has been successfully activated'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_message_inactivated', 'translation' => '  LanguageTranslate has been successfully inactivated'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_form_manage_languagetranslates', 'translation' => '  Manage languagetranslates'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_form_languagetranslates_list', 'translation' => '  List of languagetranslates'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_form_deleted_languagetranslates_list', 'translation' => '  List deleted languagetranslates'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_form_manage_deleted_languagetranslates', 'translation' => '  Manage deleted languagetranslates'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_message_delete_multiple', 'translation' => '  Selected languagetranslates have been successfully deleted.'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_message_fail_delete_multiple', 'translation' => '  Failed to delete the selected languagetranslates. Please try again.'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_message_restore_multiple', 'translation' => '  Selected languagetranslates have been successfully restored.'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_message_fail_restore_multiple', 'translation' => '  Failed to restore the selected languagetranslates. Please try again.'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_message_activate_multiple', 'translation' => '  Selected languagetranslates have been successfully activated.'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_message_fail_activate_multiple', 'translation' => '  Failed to activate the selected languagetranslates. Please try again.'],
            ['model' => ' LanguageTranslate', 'label' => 'navigation_navigation_languagetranslates', 'translation' => '  languagetranslates'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_table_model', 'translation' => '  Model'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_form_model', 'translation' => '  Model'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_form_model_placeholder', 'translation' => '  Enter model'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_table_language_id', 'translation' => '  Language'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_form_language_id', 'translation' => '  Language'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_form_language_id_placeholder', 'translation' => '  Enter language'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_table_label', 'translation' => '  Label'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_form_label', 'translation' => '  Label'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_form_label_placeholder', 'translation' => '  Enter label'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_table_translation', 'translation' => '  Translation'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_form_translation', 'translation' => '  Translation'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_form_translation_placeholder', 'translation' => '  Enter translation'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_table_created_at', 'translation' => '  Created at'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_form_created_at', 'translation' => '  Created at'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_form_created_at_placeholder', 'translation' => '  Enter created at'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_table_updated_at', 'translation' => '  Updated at'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_form_updated_at', 'translation' => '  Updated at'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_form_updated_at_placeholder', 'translation' => '  Enter updated at'],
            ['model' => ' LanguageTranslate', 'label' => 'languagetranslate_form_sync', 'translation' => '  Translation synced successfully'],
            ['model' => ' Sidebar', 'label' => 'sidebar_action_add', 'translation' => '  Add sidebar'],
            ['model' => ' Sidebar', 'label' => 'sidebar_action_show', 'translation' => '  Show sidebar'],
            ['model' => ' Sidebar', 'label' => 'sidebar_action_edit', 'translation' => '  Edit sidebar'],
            ['model' => ' Sidebar', 'label' => 'sidebar_action_delete', 'translation' => '  Delete sidebar'],
            ['model' => ' Sidebar', 'label' => 'sidebar_action_restore', 'translation' => '  Restore sidebar'],
            ['model' => ' Sidebar', 'label' => 'sidebar_message_add', 'translation' => '  Sidebar successfully created'],
            ['model' => ' Sidebar', 'label' => 'sidebar_message_show', 'translation' => '  Sidebar successfully showed'],
            ['model' => ' Sidebar', 'label' => 'sidebar_message_edit', 'translation' => '  Sidebar successfully updated'],
            ['model' => ' Sidebar', 'label' => 'sidebar_message_delete', 'translation' => '  Sidebar successfully deleted'],
            ['model' => ' Sidebar', 'label' => 'sidebar_message_restore', 'translation' => '  Sidebar successfully restored'],
            ['model' => ' Sidebar', 'label' => 'sidebar_message_activated', 'translation' => '  Sidebar has been successfully activated'],
            ['model' => ' Sidebar', 'label' => 'sidebar_message_inactivated', 'translation' => '  Sidebar has been successfully inactivated'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_manage_sidebars', 'translation' => '  Manage sidebars'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_sidebars_list', 'translation' => '  List of sidebars'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_deleted_sidebars_list', 'translation' => '  List deleted sidebars'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_manage_deleted_sidebars', 'translation' => '  Manage deleted sidebars'],
            ['model' => ' Sidebar', 'label' => 'sidebar_message_delete_multiple', 'translation' => '  Selected sidebars have been successfully deleted.'],
            ['model' => ' Sidebar', 'label' => 'sidebar_message_fail_delete_multiple', 'translation' => '  Failed to delete the selected sidebars. Please try again.'],
            ['model' => ' Sidebar', 'label' => 'sidebar_message_restore_multiple', 'translation' => '  Selected sidebars have been successfully restored.'],
            ['model' => ' Sidebar', 'label' => 'sidebar_message_fail_restore_multiple', 'translation' => '  Failed to restore the selected sidebars. Please try again.'],
            ['model' => ' Sidebar', 'label' => 'sidebar_message_activate_multiple', 'translation' => '  Selected sidebars have been successfully activated.'],
            ['model' => ' Sidebar', 'label' => 'sidebar_message_fail_activate_multiple', 'translation' => '  Failed to activate the selected sidebars. Please try again.'],
            ['model' => ' Sidebar', 'label' => 'navigation_navigation_sidebars', 'translation' => '  sidebars'],
            ['model' => ' Sidebar', 'label' => 'sidebar_table_name', 'translation' => '  Name'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_name', 'translation' => '  Name'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_name_placeholder', 'translation' => '  Enter name'],
            ['model' => ' Sidebar', 'label' => 'sidebar_table_icon', 'translation' => '  Icon'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_icon', 'translation' => '  Icon'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_icon_placeholder', 'translation' => '  Enter icon'],
            ['model' => ' Sidebar', 'label' => 'sidebar_table_permission', 'translation' => '  Permission'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_permission', 'translation' => '  Permission'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_permission_placeholder', 'translation' => '  Enter permission'],
            ['model' => ' Sidebar', 'label' => 'sidebar_table_sidebar_id', 'translation' => '  Sidebar'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_sidebar_id', 'translation' => '  Sidebar'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_sidebar_id_placeholder', 'translation' => '  Enter sidebar'],
            ['model' => ' Sidebar', 'label' => 'sidebar_table_order', 'translation' => '  Order'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_order', 'translation' => '  Order'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_order_placeholder', 'translation' => '  Enter order'],
            ['model' => ' Sidebar', 'label' => 'sidebar_table_route', 'translation' => '  Route'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_route', 'translation' => '  Route'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_route_placeholder', 'translation' => '  Enter route'],
            ['model' => ' Sidebar', 'label' => 'sidebar_table_type', 'translation' => '  Type'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_type', 'translation' => '  Type'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_type_placeholder', 'translation' => '  Enter type'],
            ['model' => ' Sidebar', 'label' => 'sidebar_table_created_at', 'translation' => '  Created at'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_created_at', 'translation' => '  Created at'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_created_at_placeholder', 'translation' => '  Enter created at'],
            ['model' => ' Sidebar', 'label' => 'sidebar_table_updated_at', 'translation' => '  Updated at'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_updated_at', 'translation' => '  Updated at'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_updated_at_placeholder', 'translation' => '  Enter updated at'],
            ['model' => ' Sidebar', 'label' => 'sidebar_table_deleted_at', 'translation' => '  Deleted at'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_deleted_at', 'translation' => '  Deleted at'],
            ['model' => ' Sidebar', 'label' => 'sidebar_form_deleted_at_placeholder', 'translation' => '  Enter deleted at'],
            ['model' => ' Sidebar', 'label' => 'translation_action_add', 'translation' => '  Add translation'],
            ['model' => ' Sidebar', 'label' => 'translation_action_syncronize', 'translation' => '  Syncronize translation'],
            ['model' => ' Sidebar', 'label' => 'navigation_navigation_settings', 'translation' => '  Settigns'],
            ['model' => ' Sidebar', 'label' => 'navigation_navigation_language', 'translation' => '  Languages'],
            ['model' => ' Sidebar', 'label' => 'navigation_navigation_state', 'translation' => '  States'],
            ['model' => ' Sidebar', 'label' => 'navigation_navigation_city', 'translation' => '  Cities'],
            ['model' => ' Sidebar', 'label' => 'navigation_navigation_sidebar', 'translation' => '  Sidebar'],
            ['model' => ' Navigation', 'label' => 'navigation_navigation_Secteur', 'translation' => '  Secteurs'],
            ['model' => ' Secteur', 'label' => 'secteur_action_add', 'translation' => '  Add secteur'],
            ['model' => ' Secteur', 'label' => 'secteur_action_show', 'translation' => '  Show secteur'],
            ['model' => ' Secteur', 'label' => 'secteur_action_edit', 'translation' => '  Edit secteur'],
            ['model' => ' Secteur', 'label' => 'secteur_action_delete', 'translation' => '  Delete secteur'],
            ['model' => ' Secteur', 'label' => 'secteur_action_restore', 'translation' => '  Restore secteur'],
            ['model' => ' Secteur', 'label' => 'secteur_message_add', 'translation' => '  Secteur successfully created'],
            ['model' => ' Secteur', 'label' => 'secteur_message_show', 'translation' => '  Secteur successfully showed'],
            ['model' => ' Secteur', 'label' => 'secteur_message_edit', 'translation' => '  Secteur successfully updated'],
            ['model' => ' Secteur', 'label' => 'secteur_message_delete', 'translation' => '  Secteur successfully deleted'],
            ['model' => ' Secteur', 'label' => 'secteur_message_restore', 'translation' => '  Secteur successfully restored'],
            ['model' => ' Secteur', 'label' => 'secteur_message_activated', 'translation' => '  Secteur has been successfully activated'],
            ['model' => ' Secteur', 'label' => 'secteur_message_inactivated', 'translation' => '  Secteur has been successfully inactivated'],
            ['model' => ' Secteur', 'label' => 'secteur_form_manage_secteurs', 'translation' => '  Manage secteurs'],
            ['model' => ' Secteur', 'label' => 'secteur_form_secteurs_list', 'translation' => '  List of secteurs'],
            ['model' => ' Secteur', 'label' => 'secteur_form_deleted_secteurs_list', 'translation' => '  List deleted secteurs'],
            ['model' => ' Secteur', 'label' => 'secteur_form_manage_deleted_secteurs', 'translation' => '  Manage deleted secteurs'],
            ['model' => ' Secteur', 'label' => 'secteur_message_delete_multiple', 'translation' => '  Selected secteurs have been successfully deleted.'],
            ['model' => ' Secteur', 'label' => 'secteur_message_fail_delete_multiple', 'translation' => '  Failed to delete the selected secteurs. Please try again.'],
            ['model' => ' Secteur', 'label' => 'secteur_message_restore_multiple', 'translation' => '  Selected secteurs have been successfully restored.'],
            ['model' => ' Secteur', 'label' => 'secteur_message_fail_restore_multiple', 'translation' => '  Failed to restore the selected secteurs. Please try again.'],
            ['model' => ' Secteur', 'label' => 'secteur_message_activate_multiple', 'translation' => '  Selected secteurs have been successfully activated.'],
            ['model' => ' Secteur', 'label' => 'secteur_message_fail_activate_multiple', 'translation' => '  Failed to activate the selected secteurs. Please try again.'],
            ['model' => ' Secteur', 'label' => 'navigation_navigation_secteur', 'translation' => '  secteurs'],
            ['model' => ' Secteur', 'label' => 'secteur_table_name', 'translation' => '  Name'],
            ['model' => ' Secteur', 'label' => 'secteur_form_name', 'translation' => '  Name'],
            ['model' => ' Secteur', 'label' => 'secteur_form_name_placeholder', 'translation' => '  Enter name'],
            ['model' => ' Secteur', 'label' => 'secteur_table_city_id', 'translation' => '  City'],
            ['model' => ' Secteur', 'label' => 'secteur_form_city_id', 'translation' => '  City'],
            ['model' => ' Secteur', 'label' => 'secteur_form_city_id_placeholder', 'translation' => '  Enter city'],
            ['model' => ' Secteur', 'label' => 'secteur_table_created_at', 'translation' => '  Created at'],
            ['model' => ' Secteur', 'label' => 'secteur_form_created_at', 'translation' => '  Created at'],
            ['model' => ' Secteur', 'label' => 'secteur_form_created_at_placeholder', 'translation' => '  Enter created at'],
            ['model' => ' Secteur', 'label' => 'secteur_table_updated_at', 'translation' => '  Updated at'],
            ['model' => ' Secteur', 'label' => 'secteur_form_updated_at', 'translation' => '  Updated at'],
            ['model' => ' Secteur', 'label' => 'secteur_form_updated_at_placeholder', 'translation' => '  Enter updated at'],
            ['model' => ' Secteur', 'label' => 'secteur_table_deleted_at', 'translation' => '  Deleted at'],
            ['model' => ' Secteur', 'label' => 'secteur_form_deleted_at', 'translation' => '  Deleted at'],
            ['model' => ' Secteur', 'label' => 'secteur_form_deleted_at_placeholder', 'translation' => '  Enter deleted at'],
            ['model' => ' State', 'label' => 'state_action_add', 'translation' => '  Add state'],
            ['model' => ' State', 'label' => 'state_action_show', 'translation' => '  Show state'],
            ['model' => ' State', 'label' => 'state_action_edit', 'translation' => '  Edit state'],
            ['model' => ' State', 'label' => 'state_action_delete', 'translation' => '  Delete state'],
            ['model' => ' State', 'label' => 'state_action_restore', 'translation' => '  Restore state'],
            ['model' => ' State', 'label' => 'state_message_add', 'translation' => '  State successfully created'],
            ['model' => ' State', 'label' => 'state_message_show', 'translation' => '  State successfully showed'],
            ['model' => ' State', 'label' => 'state_message_edit', 'translation' => '  State successfully updated'],
            ['model' => ' State', 'label' => 'state_message_delete', 'translation' => '  State successfully deleted'],
            ['model' => ' State', 'label' => 'state_message_restore', 'translation' => '  State successfully restored'],
            ['model' => ' State', 'label' => 'state_message_activated', 'translation' => '  State has been successfully activated'],
            ['model' => ' State', 'label' => 'state_message_inactivated', 'translation' => '  State has been successfully inactivated'],
            ['model' => ' State', 'label' => 'state_form_manage_states', 'translation' => '  Manage states'],
            ['model' => ' State', 'label' => 'state_form_states_list', 'translation' => '  List of states'],
            ['model' => ' State', 'label' => 'state_form_deleted_states_list', 'translation' => '  List deleted states'],
            ['model' => ' State', 'label' => 'state_form_manage_deleted_states', 'translation' => '  Manage deleted states'],
            ['model' => ' State', 'label' => 'state_message_delete_multiple', 'translation' => '  Selected states have been successfully deleted.'],
            ['model' => ' State', 'label' => 'state_message_fail_delete_multiple', 'translation' => '  Failed to delete the selected states. Please try again.'],
            ['model' => ' State', 'label' => 'state_message_restore_multiple', 'translation' => '  Selected states have been successfully restored.'],
            ['model' => ' State', 'label' => 'state_message_fail_restore_multiple', 'translation' => '  Failed to restore the selected states. Please try again.'],
            ['model' => ' State', 'label' => 'state_message_activate_multiple', 'translation' => '  Selected states have been successfully activated.'],
            ['model' => ' State', 'label' => 'state_message_fail_activate_multiple', 'translation' => '  Failed to activate the selected states. Please try again.'],
            ['model' => ' State', 'label' => 'navigation_navigation_state', 'translation' => '  states'],
            ['model' => ' State', 'label' => 'state_table_name', 'translation' => '  Name'],
            ['model' => ' State', 'label' => 'state_form_name', 'translation' => '  Name'],
            ['model' => ' State', 'label' => 'state_form_name_placeholder', 'translation' => '  Enter name'],
            ['model' => ' State', 'label' => 'state_table_created_at', 'translation' => '  Created at'],
            ['model' => ' State', 'label' => 'state_form_created_at', 'translation' => '  Created at'],
            ['model' => ' State', 'label' => 'state_form_created_at_placeholder', 'translation' => '  Enter created at'],
            ['model' => ' State', 'label' => 'state_table_updated_at', 'translation' => '  Updated at'],
            ['model' => ' State', 'label' => 'state_form_updated_at', 'translation' => '  Updated at'],
            ['model' => ' State', 'label' => 'state_form_updated_at_placeholder', 'translation' => '  Enter updated at'],
            ['model' => ' State', 'label' => 'state_table_deleted_at', 'translation' => '  Deleted at'],
            ['model' => ' State', 'label' => 'state_form_deleted_at', 'translation' => '  Deleted at'],
            ['model' => ' State', 'label' => 'state_form_deleted_at_placeholder', 'translation' => '  Enter deleted at'],
            ['model' => ' Navigation', 'label' => 'navigation_navigation_templates', 'translation' => '  Templates'],
        ];

        foreach ($translations as $translate) {
            LanguageTranslate::firstOrCreate(
                ['label' => $translate['label']],
                [
                    'model' => $translate['model'],
                    'translation' => $translate['translation'],
                ],
            );
        }
    }
}
